- src/private/conversion.nim
- src/private/stdlib_bitops.nim
- src/private/uint_binary_ops.nim
- src/private/uint_bitwise_ops.nim
- tests/test_muldiv.nim
Currently cannot be tested on "-d:mpuint_test" flag as it requires for uint128 a working nested initialization like `MpUintImpl[MpUintImpl[uint32]]`
> Faster division algorithm

- src/io.nim
- src/private/uint_div.nim
- stint.nimble
- tests/internal.nim
- tests/internal_uint_div.nim
- tests/test_uint_muldiv.nim
Fixes random failures in Quicktest: #30 and add test to internal non-publicly exposed algo div2n1n.
The CI is still failing due Nim compiler string changes, this is fixed in master by https://github.com/status-im/nim-stint/commit/d68c0bf44a53dad565210523abb77ba211f769d7
> Fix modulo failures

- .gitignore
- src/private/uint_mul.nim
- stint.nimble
- tests/property_based.nim
- tests/property_based_uint256.nim
- tests/ttmath_compat.nim
This adds fuzz testing vs TTMath.
It requires the latest Nimbus patch: https://github.com/status-im/Nim/commit/60db1a899c3b15df677092e90be982bf6a60a9fd
There is still a C++ only SIGSEGV with nil string/json (?):
```
<...>/.nimble/pkgs/quicktest-0.18.0/quicktest.nim(414, 47) Hint: simpleGetOrDefault(parseJson(serialized397017), "args") --> 'getOrDefault(parseJson(serialized397017), "args")' [Pattern]
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
Also unfortunately, to add this to CI, Stint must require quicktest and ttmath, though if they are not used it shouldn't force C++ compilation. Feature request here: https://github.com/nim-lang/nimble/issues/482.
> Add uint256 fuzz test vs TTMath

- src/io.nim
- src/private/as_signed_words.nim
- src/private/as_words.nim
We can't use plain restrict, as that is not a C++ keyword and would prevent us compiling to C++ in the future (not that we actually want to).
`__restrict__` is not understood by VCC
`__restrict` should be understood by all compilers.
> Restrict pragma: use VCC + GCC + LLVM compatible syntax

- src/private/uint_mul.nim
> 32-bits - use guaranted 64-bit types in VM for mul

- stint/private/uint_exp.nim
- stint/uint_public.nim
- tests/property_based.nim
- tests/property_based_uint256.nim
- tests/test_uint_exp.nim
Solves the unimplemented warning and several failing tests after the switch to Stint in Nimbus: https://github.com/status-im/nimbus/commit/9fc80cb6c9516d013069aadacaef5b9b84266c43
> Add exponentiation

- stint.nim
- stint/int_public.nim
- stint/modular_arithmetic.nim
- stint/private/int_comparison.nim
- stint/private/uint_comparison.nim
- stint/private/uint_exp.nim
- stint/uint_public.nim
- tests/test_int_comparison.nim
- tests/test_uint_comparison.nim
- tests/uint_modular_arithmetic.nim
This adds the following:
- Efficient `isEven` and `isOdd` proc
- `addmod`, `submod`, `mulmod`, `expmod`
What is not covered:
1. A modular template that transforms all operation in scope in their modulo equivalent
```Nim
proc addmod*[T: SomeInteger](a, b, m: T): T =
let a_m = if a < m: a
else: a mod m
if b == 0.T:
return a_m
let b_m = if b < m: b
else: b mod m
let b_from_m = m - b_m
if a_m >= b_from_m:
return a_m - b_from_m
return m - b_from_m + a_m
proc submod*[T: SomeInteger](a, b, m: T): T =
let a_m = if a < m: a
else: a mod m
if b == 0.T:
return a_m
let b_m = if b < m: b
else: b mod m
if a_m >= b_m:
return a_m - b_m
return m - b_m + a_m
template modulo*[T:SomeInteger](modulus: T, body: untyped): untyped =
let m = modulus
template `+`(a, b: T): T =
addmod(a, b, modulus)
template `-`(a, …
```
> Modular arithmetic

- stint.nim
- stint/literals_stint.nim
Follow-up on #49
Literals are supported by default ( `let a = 10.u256; echo a + 1`) while non-literals would require importing `lenient_stint` from #49 (`let a = 10.u256; let b = 1; echo a + b`)
> Add overloads for literals only

- stint/lenient_stint.nim
- stint/mixed_types_ops.nim
Solve #15 
Introduce optional mixed types syntactic sugar.
The goal is to keep a natural syntax as much as possible and avoid having conversion everywhere when working with mixed uint256, int and uint in a codebase for example.
The file must be explicitly imported with `import stint/mixed_types_ops` so that when strong static typing is preferred or for debugging, conversions are required to be explicit.
> Add optional mixed types syntactic sugar

- stint/io.nim
- stint/private/as_signed_words.nim
- stint/private/as_words.nim
- stint/private/initialization.nim
- stint/uint_public.nim
This allows compile-time construction of Uint256.
Unfortunately Int256 are much more tricky.
Benefits:
- Nimbus const will be actually constants https://github.com/status-im/nimbus/blob/master/nimbus/constants.nim. This means that they can be inlined at compile-time and we can make Nimbus more restrictive regarding side-effects.
> Start on allowing compile-time stint. Works for Uint256

- benchmarks/bench_mod.nim
- stint/private/as_signed_words.nim
- stint/private/as_words.nim
- stint/private/bithacks.nim
- stint/private/int_addsub.nim
- stint/private/int_bitwise_ops.nim
- stint/private/int_comparison.nim
- stint/private/uint_bitwise_ops.nim
- stint/private/uint_comparison.nim
This PR allows compile-time evaluation for Uint for all procs (including +, *, div, mod, or, and, xor, ...).
Ints are not covered.
Changing Stint backend to C arrays, which I tried yesterday in [another branch](https://github.com/status-im/nim-stint/tree/compile-time-and-js-compat) led to much too many issues, https://github.com/nim-lang/Nim/issues/8052, https://github.com/nim-lang/Nim/issues/8053 until I was stuck with how to slice half of the array to do a simple `+=`: `foo.lo += bar.lo`
https://github.com/status-im/nim-stint/blob/fec21907ea0870216bf95ab61b7ed79648883b99/stint/private/datatypes.nim#L49-L155
I implemented a macro that gets all the "leaves" of a uint or int in big endian order, so for a uint256 I get [foo.hi.hi, foo.hi.lo, foo.lo.hi, foo.lo.lo].
I replaced all the …
> Uint - allow compile-time evaluation for all procs

- stint/io.nim
- tests/test_io.nim
The new `to` operators that can be used to constuct Stint types from
regular integer types. These are intented for usage in generic code
such as rlp.nim
Also fixes a bug preventing construction of Stint values from unsigned
integers (because they lack an unary `-` operator).
> Add explicit generic conversion operators

- stint/private/uint_mul.nim
Currently on 32 bit systems the follow code doesn't perform as expected:
```
import stint
proc doTest(stintType: typedesc) =
var
a = fromHex(stintType, "0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff")
b = fromHex(stintType, "0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff")
c = a * b
echo c.toHex
doTest(StUInt[2048])
doTest(UInt256)
```
This small PR allows `stint` to perform correctly in 32 bit.
> Fix multiplication on 32 bit systems

- stint/endians2.nim
- stint/intops.nim
- stint/io.nim
- stint/private/compiletime_helpers.nim
- stint/private/datatypes.nim
- stint/private/endians2_priv.nim
- stint/private/int_bitwise_ops.nim
- stint/private/int_div.nim
- stint/private/int_mul.nim
- tests/all_tests.nim
- tests/test_helpers.nim
- tests/test_int_addsub.nim
- tests/test_int_bitwise.nim
- tests/test_int_boundchecks.nim
- tests/test_int_comparison.nim
- tests/test_int_muldiv.nim
- tests/test_io.nim
- tests/test_uint_addsub.nim
- tests/test_uint_bitops2.nim
- tests/test_uint_bitwise.nim
- tests/test_uint_comparison.nim
- tests/test_uint_endians2.nim
- tests/test_uint_exp.nim
- tests/test_uint_modular_arithmetic.nim
- tests/test_uint_muldiv.nim
The goal of this  PR is to have 100% coverage for all exported API to pass compile time test.
The compile time helpers implementation might be not efficient, but first make it run then make it run fast.
As a bonus, it also improve runtime coverage.
zero, negative numbers, hi and lo tests also added if possible.
Inputs are welcome.
> [RDY] improve compile time tests coverage

- stint/io.nim
- tests/all_tests.nim
- tests/test_conversion.nim
- tests/test_int_addsub.nim
- tests/test_int_comparison.nim
summary of this PR:
implement 4 constructors:
- stuint to stuint
- stint to stuint
- stint to stint
- stuint to stint
all new constructors can convert smaller to bigger ints or bigger to smaller ints, including conversion to equal bitsize.
> fixes #94, implement conversion constructor

- stint/private/datatypes.nim
unblocks https://github.com/nim-lang/Nim/pull/18050 which fixes the long-standing generic sandwich problem in nim
this is forward and backward compatible.
https://github.com/nim-lang/Nim/pull/18050 also addresses the following:
> export IntImpl, intImpl, UintImpl, uintImpl, bitsof # TODO: remove the need to export those
by binding symbol `uintImpl` from where it's called in:
```nim
type
StUint*[bits: static[int]] = object
data*: uintImpl(bits)
```
so that `uintImpl` won't need to be exposed to clients of `StUint`
> fix stint for https://github.com/nim-lang/Nim/pull/18050

- tests/test_int_addsub.nim
I suspect Nim int/int32 in the VM do not use int64 anymore and so we are now affected by #92 in the compile-time VM as well as the test failure is:
https://github.com/status-im/nim-stint/runs/4783712651?check_suite_focus=true#step:11:105
With the test being L231
https://github.com/status-im/nim-stint/blob/e17113fb31bc90780ce89ab5de0f4a60d40d3aa1/tests/test_int_addsub.nim#L226-L233
And with signed integer, the lowest negative int cannot be negated. i.e. for int8 there is -128 but the highest positive int is 127.
> Fix 32-bit failure on Nim 1.6

- .github/workflows/ci.yml
https://github.com/actions/runner-images/issues/6002
> update GitHub Actions CI images from deprecated Ubuntu 18.04 to 20.04

- stint/io.nim
- tests/test_io.nim
Hex strings starting with `0b` would erroneously treated as binary numbers by `skipPrefixes`. 
An error should be raised only when `radix` is not 2 or 16, while the `0b` prefix should be skipped only when `radix = 2`.
Related issue https://github.com/status-im/nim-web3/issues/63.
> fix(skipPrefixes): fix erroneous strip of 0b in hex numbers

- README.md
- stint.nimble
First versioned release to celebrate the increased capabilities of `nimble` to work with versions ;)
This release is "nearly" feature-complete but still has some open API/ABI questions, in particular around endians, bitops and other convenience features.
Ideally, a 1.0 release would also not carry a stew dependency but rather see that part of stew exported to its own
[intops](https://github.com/status-im/nim-stew/pull/187) library that would gather all the low-level stuff and define a common minimally supported API for all kinds of integers, native or not.
> Initial release (v0.8.0)

- stint/literals_stint.nim
- stint/private/custom_literal.nim
- tests/test_features.nim
Trying to use `0'u256` results in `Error: index 1 not in 0 .. 0` because the literal parsing function assumes min length 2 when the literal starts with a 0. Fix that incorrect assumption.
> Avoid index error when creating zero literal
